### ISSUE TITLE
cannot resolve symbol DaggerAppComponent

### ISSUE THREAD

**Issue by bananaCaptain** [erikcaffrey/Dagger2-MVP-Sample#1]
```
component = DaggerAppComponent.builder().appModule(new AppModule(this)).build(); error
```

**Comment by erikjhordan-rey** [comment]
@bananaCaptain This example works correctly I just checked, Did you try to rebuild the project?                                     You have to go  Build -> Rebuild project.  Remember that these classes are generated at compile-time.

**Comment by IdioticMadman** [comment]
@erikcaffrey I am just trying to move the **CategoryActivityComponent** to another package which does not with the **CateoryActivity**. And then this error come out . I think you should change this line 
https://github.com/erikcaffrey/Dagger2-MVP-Sample/blob/master/app/build.gradle#L38 to _"apt 'com.google.dagger:dagger-compiler:2.0'"_ to suport while those two file doesn't in same package

**Comment by erikjhordan-rey** [comment]
@IdioticMadman the library would not have to be a problem maybe you can try rebuild project, you don't need to create or move another component is just a simple example also there are no many dependencies that must be separated and remember maintain the things simples.

**Comment by IdioticMadman** [comment]
Yeah, That's OK.Thanks

**Comment by dilip90** [comment]
@erikcaffrey , thanks rebuild is solution.

**Comment by erikjhordan-rey** [comment]
@dilip90 @IdioticMadman @bananaCaptain https://erikcaffrey.github.io/ANDROID-kata-dagger2/

**Comment by aneeshATgithub** [comment]
Hello, clean and rebuild is not a solution for me, and the error stays there.


This is my error log:


Error:(8, 47) error: cannot find symbol variable DaggerAppComponent
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.


Can anyone suggest me an alternative or a workaround for this?

**Comment by erikjhordan-rey** [comment]
@aneeshATgithub 

The class `DaggerAppComponent` is a generated class on compile time. Try invalidate caches an restart, and rebuild. if it doesn't works maybe your problem is about version of sdk btw I updated the project to the last version of support library and is working https://github.com/erikcaffrey/Dagger2-MVP-Sample/pull/6 

I also have another sample to learn Dagger 2  -> https://github.com/erikcaffrey/Kata-Dagger2-MarioKart

**Comment by aneeshATgithub** [comment]
I had tried invalidate caches an restart, also clean and rebuild.
Finally I updated buildToolsVersion to  "26.0.2". But the error not gone.

**Comment by homandiy** [comment]
Ctrl+F9

**Comment by albert0m** [comment]
I had to clean the project and after that I get this error from Studio, even though the files are present. Tried to Invalidate / Restart, Clean, Rebuild.. still get the error from studio.

**Comment by homandiy** [comment]
What's error?

**Comment by albert0m** [comment]
```
error: cannot find symbol
import com.mypackage.DaggerAppComponent;
```

I went through most of the answer on stackoverflow but it looks I broke it.

**Comment by sandeep287** [comment]
compile 'com.google.dagger:dagger:2.8'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.8'

i will already used this  gradle but DaggerAppComponent not support.
please help 
thanks in advance

**Comment by homandiy** [comment]
Where is your project address at Github? Let me try.

Homan Huang

**Comment by erikjhordan-rey** [comment]
@sandeep287 Hey man! 

First of all thanks for visit this repository, I hope you found it useful. 

I Upgrated the project some minutes ago and it's working 😃. 
<img width="301" alt="imagen" src="https://user-images.githubusercontent.com/5893477/39851469-9878b380-53dc-11e8-9767-a6218fa72988.png">
!

Remember the class DaggerAppComponent is a generated class on compile time so you should do:

<img src="https://user-images.githubusercontent.com/5893477/39851417-44eeb3a4-53dc-11e8-8e3b-df0bfc1dfd48.png" width="260">

I hope it solves your problem.

**Comment by attifmazhar** [comment]
Invalidate and Restart

**Comment by vishalvj9** [comment]
invalidate & cache restart is not valid solution I have started new project setup dagger same problem raise daggerComponent not find the symbols.

**Comment by balusreekanth** [comment]
_**Make Project**_  and  **_Rebuild Project_**  So DaggerAppComponent will be generated .

**Comment by freshindee** [comment]
1.Clean the project
2.Rebuild
3.File-->Invalidate and Restart

**Comment by Hossam47** [comment]
Make sure that dependencies added in your gradle

```
    implementation 'com.google.dagger:dagger-android:2.15'
    implementation 'com.google.dagger:dagger-android-support:2.13'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.16'
```

**Comment by homandiy** [comment]
If you are in test folder, you don't need to rebuild it again; ignore the red line; run it. For example,
` 
    fun daggerInjection(app: Application) : TestRetrofitComponent {
        return DaggerTestRetrofitComponent.builder()
            .application( app )
            .testAppModule(TestAppModule())
                // for test purpose: 2 second timeout
            .apiModule(ApiModule(testUrl, 2, 2))
            .build()
    }
`
my test component:
`
@Singleton
@Component(modules = [
    AndroidSupportInjectionModule::class,
    ApiModule::class,
    TestAppModule::class
])
interface TestRetrofitComponent : AppointmentAppComponent {

    @Component.Builder
    interface Builder {

        @BindsInstance
        fun application(application: Application): Builder

        fun apiModule(apiModule: ApiModule): Builder

        fun testAppModule(testAppModule: TestAppModule): Builder

        fun build(): TestRetrofitComponent // Type
    }

    // Dagger injector
    fun inject(test: MainActivityRetrofitTest)
}

@Module
class TestAppModule {
    @Singleton
    @Provides
    fun giveMockWebServer(): HomanMockWebServer = HomanMockWebServer()
}
`
Inject to the test class:
`
    @Before
    fun setUp() {
        context = InstrumentationRegistry.getInstrumentation().targetContext
        val testApp = context.applicationContext as DebugAppointmentApplication?

        // Dagger component
        val component = daggerInjection(testApp!!)

        testApp.setTestComponent(component)

        // Dagger shot: init all variables
        component.inject(this)
`
